### ISSUE TITLE
Dropbox Sync Speed

### ISSUE THREAD

**Issue by T3chie-404** [nextcloud/integration_dropbox#13]
Hello, Thanks for all your work! 

I have my NextCloud server sitting in a data center on a 10gbps port and trying to sync my 600 GB dropbox account over. I figured it would be faster than its going but don't know if this is due to restrictions on Dropbox, my server, or nextcloud or the plugin. My system is only using 20-30mbps and after 3 days has only transferred ~20GB. It seems to stop transferring after some amount of time (6 hours?) and restarting in the nextcloud settings it will take off again.

Is there any testing that has been done or results anyone can share of faster speeds than I am seeing?

Thanks again!

**Comment by marcelklehr** [comment]
Dropbox has limits on how fast we can go, IIRC.
