### ISSUE TITLE
Dropbox import process will begin soon 

### ISSUE THREAD

**Issue by LRWphil** [nextcloud/integration_dropbox#15]
Hi, 
after the first start the process migrated ca. 300MB of files from my dropbox. Then it stopped.
I then checked the Report in /settings/admin/logging/ 
(there are only 2 old erros for Version Manager and TrashManager)
and started the whole process again.

_Authentication
 Connected as ... (Check)
Dropbox storage
 Dropbox storage size: 1 TiB
0 files imported 
Dropbox import process will begin soon_

No Progress ...
Hosting: nx40 by hetzner

thank you for your help

**Comment by a-wendler** [comment]
I have the same problem. Also on Hetzner Hosting.

**Comment by JohannCR** [comment]
Same for me. Fresh NC install.

**Comment by JohannCR** [comment]
Well, It seems to have worked now, but I don't know if it's what I did (using my own oauth app) or just a coincidence. You may try it and see if it solves it for you. Go to https://www.dropbox.com/developers/apps and create an app. copy the key and secret (no need for redirect URI or any other setting) and put them in the dropbox section of "connected accounts" in Nextcloud.
Does that work for you ?

**Comment by LRWphil** [comment]
I created an app, copied/pasted the key and secret in "connected accounts", renewed the connection in "Data migration", hit go and

_0 files imported 
Dropbox import process will begin soon_

**Comment by JohannCR** [comment]
Then another thing to try is to change the cronjob parameters. Default is Ajax cron which makes NextCloud very slow and I've found it very unreliable too...
The best is to use system cron but I can't guide you through its use though, because it depends on your setup. On Synology Nas it's easy using task scheduler. That's what I did and NC is much faster to navigate and for data importations too.
Dont know much about webcron, you could try it also, some seem to use it with success.
If that doesn't do it either, we'll need someone else to throw ideas...

**Comment by a-wendler** [comment]
Hey, thanks a lot. I solved it the boring way by moving the Dropbox files
to the Nextcloud folder on my hard disk and then letting it synch those
files up.

I use a hosted version of Nextcloud so can’t go too much into the depth of
system.

Thx anyway.

Johann ***@***.***> schrieb am Di. 14. Dez. 2021 um 11:06:

**Comment by schanceee** [comment]
Hey guys I have the same problem except for me it just does not start at all. I created the app in dropbox, filled the key and secrets as indicated but it doesn't start and i don't even see an error in the logs. @JohannCR can you please provide more details on how to change the cronjob parameters?

**Comment by Petapton** [comment]
> Hey guys I have the same problem except for me it just does not start at all. I created the app in dropbox, filled the key and secrets as indicated but it doesn't start and i don't even see an error in the logs. @JohannCR can you please provide more details on how to change the cronjob parameters?

See [this page](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/background_jobs_configuration.html).

**Comment by marcelklehr** [comment]
Hello :wave: 
Who still has this problem with the latest version of the app while using cron job background execution?
