### ISSUE TITLE
Sync problems with case sensitive Nextcloud host

### ISSUE THREAD

**Issue by normen** [nextcloud/integration_dropbox#9]
Hey,

first of all thanks for this software!

I noticed that there seem to be some issues when the NextCloud instance has a filesystem with case sensitivity enabled. I am getting double folders which in turn won't sync properly with clients that don't have case sensitivity support. The latter is probably more of a problem of NextCloud however I don't see any double folders in DropBox so I suppose the flattening should happen at the stage of this plugin already.

Cheers,
Normen

**Comment by Roshak** [comment]
Same here, 

i have duplicated folders one with a capitalized first letter and the other one with a lowercase first letter.

In my dropbox folders the folder is just one with a capitalized first letter.

thanks!

**Comment by feenstaub-lb** [comment]
I have exactly the same problem: the sync works fine, only the thing with the case sensitive folder names (as described above), would be great if there was a solution here.

**Comment by feenstaub-lb** [comment]
could this maybe the solution:

> Also, while Dropbox is case-insensitive, it makes efforts to be case-preserving. Metadata.name will contain the correct case. Metadata.path_display usually will contain the correct case, but sometimes only in the last path component. If your app needs the correct case for all path components, it can get it from the Metadata.name or last path component of each relevant Metadata.path_display entry. 

source: [https://www.dropbox.com/developers/documentation/http/documentation]

**Comment by johnnyasantoss** [comment]
In my use case, I was trying to export all my data from Dropbox. So what I did was:

1) Export everything from Dropbox, zipping all of it.
2) Unzipped all of my data to a vfat fs ([link](https://unix.stackexchange.com/a/195354/256002)) overwriting files (in my case they were all the same) and merging folders with the same name
3) Synced all of my files from that fs to Nextcloud and voilà

WARNING: This probably will lead to data loss - in my case it was fine, so analyze your own yourself.

I know this doesn't help the extension, but, to me, I wanted the files in my Nextcloud instance and this did it. 🤷🏾‍♂️

**Comment by feenstaub-lb** [comment]
> I know this doesn't help the extension, but, to me, I wanted the files in my Nextcloud instance and this did it. 🤷🏾‍♂️

Hey, that's not the solution for your nextcloud extension - but though very helpful. Thank you very much for your response!

**Comment by hvisage** [comment]
> In my use case, I was trying to export all my data from Dropbox. So what I did was:

>     2. Unzipped all of my data to a vfat fs ([link](https://unix.stackexchange.com/a/195354/256002)) overwriting files (in my case they were all the same) and merging folders with the same name

The VFAT extraction step is technically not needed, just extract inside the NextCloud folder - but that is NOT the issue/problem we try to solve, but rather to have the user import from their dropbox "seamlessly" which is the case this case preserving fails with - also had multiple duplicates (case sensitive duplicates that is) from a non-uplicate DropBox once imported into NC 24.

Wish there was a "Case Insensitive" option for NC

**Comment by marcelklehr** [comment]
This is an issue with Nextcloud, not this app.
